[build]
  base = "."
  command = "npm run build:netlify"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

# For SPA (Single Page Application) - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
